Develop
mshmwr/taipei-day-trip-website pull request #2
Opened 2021-04-23 12:15 UTC by mshmwr

part 1-2

2021-04-23 19:39 UTC, mshmwr commented
http://18.219.195.102:3000/api/attractions?page=1
http://18.219.195.102:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93
http://18.219.195.102:3000/api/attraction/100

2021-04-23 20:54 UTC, cwpeng requested changes
關鍵字搜尋，會一次顯示所有資料，分頁沒有效果，例如：
http://18.219.195.102:3000/api/attractions?page=0&keyword=臺北
http://18.219.195.102:3000/api/attractions?page=1&keyword=臺北

2021-04-23 20:56 UTC, cwpeng requested changes
這裡的 else 可以和上面的 if 區塊一樣做分頁處理。

2021-04-23 20:57 UTC, cwpeng commented on app.py
> +        else:
這裡的 else 可以和上面的 if 區塊一樣做分頁處理。

2021-04-24 18:59 UTC, mshmwr reviewed
修正：關鍵字搜尋，會一次顯示所有資料，分頁沒有效果

2021-04-24 18:59 UTC, mshmwr commented on app.py
> +        else:
commit number: 68e71874501dde24e4f03d22bbcd4428998eb69a 已修正
修正項目：
1. 篩選12筆資料時，LIMIT的範圍有錯
2. 關鍵字搜尋結果未做分頁

2021-04-24 19:17 UTC, cwpeng commented
幾乎完成了，主要的部分看起來都 OK，但你的資料中的 address 似乎是變成日期了。

請修正完之後，在重新發 review 的要求給我哦 ~

2021-04-25 06:26 UTC, cwpeng commented
網站似乎連不上，修復後和我說 ~

2021-04-25 07:42 UTC, cwpeng approved these changes
OK. Good Fix.

2021-04-25 08:07 UTC, merged