Develop
mshmwr/taipei-day-trip-website pull request #5
Opened 2021-05-13 16:01 UTC by mshmwr

李宜蓁
http://18.219.195.102:3000/
http://18.219.195.102:3000/attraction/220

2021-05-13 16:32 UTC, cwpeng requested changes
註冊帳號時會出現 serverError 無法運作，另外密碼請使用密碼輸入框，請修正哦 ~

2021-05-14 16:50 UTC, cwpeng requested changes
我試著重複註冊相同的 Email，你的伺服器會出現 server error。我看了你的程式，在某些情況下連結會無法關閉 ( return 的敘述在關閉之前執行，就不會執行關閉的動作 )

修正後可先多方測試，註冊、登入、重複註冊、登入，登入失敗等等動作。

2021-05-15 12:08 UTC, mshmwr commented
> 我試著重複註冊相同的 Email，你的伺服器會出現 server error。我看了你的程式，在某些情況下連結會無法關閉 ( return 的敘述在關閉之前執行，就不會執行關閉的動作 )
> 
> 修正後可先多方測試，註冊、登入、重複註冊、登入，登入失敗等等動作。

重新上傳後有測試過了，再請老師幫忙確認一遍~謝謝

2021-05-15 15:47 UTC, cwpeng approved these changes
好哦，看起來沒問題了，這樣就可以 :)

額外建議是在滑鼠移動到註冊/登入的文字時，把滑鼠改成手的圖示，體驗會比較好 ~

2021-05-16 04:08 UTC, mshmwr commented
> 好哦，看起來沒問題了，這樣就可以 :)
> 
> 額外建議是在滑鼠移動到註冊/登入的文字時，把滑鼠改成手的圖示，體驗會比較好 ~

好的~這邊會再做修改，謝謝老師^^

2021-05-16 04:08 UTC, merged